FROM mcr.microsoft.com/devcontainers/typescript-node:0-18

RUN sudo apt-get update && \
    sudo apt-get upgrade && \
    sudo apt-get install build-essential nodejs npm libcurl4-gnutls-dev libicu-dev zlib1g-dev pkg-config cmake subversion

